# Generated by Django 6.0 on 2025-12-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('concluded', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(related_name='tasks', to='task.tag')),
            ],
        ),
    ]
